import Head from "next/head"
import { BsFillMoonStarsFill } from "react-icons/bs"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portofoliu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="md:p-10">
        <section className="flex justify-between relative shadow-2xl md:p-10 p-5  bg-gradient-to-tr  from-indigo-700 to-indigo-300">
          <BsFillMoonStarsFill
            className=" text-xl rounded-full"
            
          />
          <h2 className=" font-bold text-1xl font-mono text-black">
            DEVELOPEDBYIUS
          </h2>
        </section>
      </main>
    </div>
  )
}
